
    create table cart_items (
        id bigint generated by default as identity,
        price float,
        qtd integer,
        cart_id bigint,
        product_id bigint,
        cart_item_id bigint,
        primary key (id)
    );

    create table carts (
        id bigint generated by default as identity,
        customer_id bigint,
        primary key (id)
    );

    create table checkouts (
        id bigint generated by default as identity,
        customer_id bigint,
        primary key (id)
    );

    create table checkouts_discounts (
        checkouts_id bigint not null,
        discounts_id bigint not null
    );

    create table customer (
        c_d_id integer not null,
        c_id bigint not null,
        c_w_id integer not null,
        c_balance float,
        c_credit varchar(255),
        c_discount float,
        c_last varchar(255),
        c_ytd_payment float,
        primary key (c_d_id, c_id, c_w_id)
    );

    create table customers (
        id bigint generated by default as identity,
        primary key (id)
    );

    create table customers_checkouts (
        customers_id bigint not null,
        checkouts_id bigint not null
    );

    create table discounts (
        id bigint generated by default as identity,
        primary key (id)
    );

    create table discounts_checkouts (
        discounts_id bigint not null,
        checkouts_id bigint not null
    );

    create table district (
        d_id integer not null,
        d_w_id integer not null,
        d_next_o_id integer,
        d_tax float,
        d_ytd float,
        primary key (d_id, d_w_id)
    );

    create table history (
        id bigint not null,
        h_amount float,
        h_c_d_id integer,
        h_c_id integer,
        h_c_w_id integer,
        h_d_id integer,
        h_data varchar(255),
        h_date bigint,
        h_w_id integer,
        primary key (id)
    );

    create table item (
        i_id integer generated by default as identity,
        i_data varchar(255),
        i_name varchar(255),
        i_price float,
        primary key (i_id)
    );

    create table new_orders (
        no_d_id integer not null,
        no_o_id integer not null,
        no_w_id integer not null,
        primary key (no_d_id, no_o_id, no_w_id)
    );

    create table order_line (
        ol_d_id integer not null,
        ol_number integer not null,
        ol_o_id integer not null,
        ol_w_id integer not null,
        ol_amount float,
        ol_dist_info float,
        ol_i_id integer,
        ol_quantity integer,
        ol_supply_w_id integer,
        primary key (ol_d_id, ol_number, ol_o_id, ol_w_id)
    );

    create table orders (
        o_d_id integer not null,
        o_id integer not null,
        o_w_id integer not null,
        o_c_id integer,
        o_ol_cnt integer,
        primary key (o_d_id, o_id, o_w_id)
    );

    create table products (
        id bigint generated by default as identity,
        description varchar(255),
        name varchar(255),
        price double,
        primary key (id)
    );

    create table stock (
        s_i_id integer not null,
        s_w_id integer not null,
        s_data varchar(255),
        s_dist varchar(255),
        s_quantity integer,
        primary key (s_i_id, s_w_id)
    );

    create table stock_item (
        id bigint not null,
        available integer not null,
        product_id bigint,
        primary key (id)
    );

    create table warehouse (
        w_id integer generated by default as identity,
        w_tax float,
        w_ytd float,
        primary key (w_id)
    );

    alter table cart_items 
        add constraint FK_4p7dd2p61wsdx9j35wp6sugqr 
        foreign key (cart_id) 
        references carts;

    alter table cart_items 
        add constraint FK_stjbkkh1eftd036p0v219glxw 
        foreign key (product_id) 
        references products;

    alter table cart_items 
        add constraint FK_r0m57kbvakqw6onqy3qnqo7xt 
        foreign key (cart_item_id) 
        references checkouts;

    alter table cart_items 
        add constraint FK_r0m57kbvakqw6onqy3qnqo7xt 
        foreign key (cart_item_id) 
        references carts;

    alter table carts 
        add constraint FK_88sv4i13lo80s74ox7rsb5a2c 
        foreign key (customer_id) 
        references customers;

    alter table checkouts 
        add constraint FK_lfp35njpy1giwh3k0wgwn9kjk 
        foreign key (customer_id) 
        references customers;

    alter table checkouts_discounts 
        add constraint FK_gcopm6ep47tkjl2vq1292tdrp 
        foreign key (discounts_id) 
        references discounts;

    alter table checkouts_discounts 
        add constraint FK_h4n0jwigp796ot4xpibxbl00x 
        foreign key (checkouts_id) 
        references checkouts;

    alter table customers_checkouts 
        add constraint FK_a7x29yy023a6fom2i9cje26vs 
        foreign key (checkouts_id) 
        references checkouts;

    alter table customers_checkouts 
        add constraint FK_5wxokv68sm3afrm1mvlxoiibc 
        foreign key (customers_id) 
        references customers;

    alter table discounts_checkouts 
        add constraint FK_swo4cas9hn7pcdhhskc5b973t 
        foreign key (checkouts_id) 
        references checkouts;

    alter table discounts_checkouts 
        add constraint FK_82c6x6qtsw995axbe5g8t3w15 
        foreign key (discounts_id) 
        references discounts;

    alter table stock_item 
        add constraint FK_ix9eis736yken28inqb667sh 
        foreign key (product_id) 
        references products;

    create sequence hibernate_sequence;
