package dk.ku.di.dms.vms.web_common.runnable;

import dk.ku.di.dms.vms.web_common.meta.Issue;
import dk.ku.di.dms.vms.web_common.meta.NetworkObject;

import java.util.concurrent.ArrayBlockingQueue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;
import java.util.logging.Logger;

/**
 * Abstract class that provides common features for server classes
 */
public abstract class SignalingStoppableRunnable extends StoppableRunnable {

    /**
     * Protocol result. Now also any result from a thread...
     */
    public static final byte NO_RESULT = 0;
    public static final byte FINISHED = 1;

    protected final Logger logger = Logger.getLogger(this.getClass().getName());

    public final CustomUncaughtExceptionHandler exceptionHandler;

    // queue serves as a channel to respond the calling thread
    protected final BlockingQueue<Byte> signal;

    // internal events generated by other threads, such as writers, e.g., channel closed, unreachable node, etc
    protected final BlockingQueue<Issue> issueQueue;

    public SignalingStoppableRunnable() {
        super();
        this.signal = new ArrayBlockingQueue<>(1);
        this.exceptionHandler = new CustomUncaughtExceptionHandler();
        this.issueQueue = new LinkedBlockingQueue<>();
    }

    /**
     * Blocks the caller until this thread finishes its work.
     * @return A byte representing the result
     */
    public Byte getResult() throws InterruptedException {
        return signal.take();
    }

    /**
     * Callback to log error
     * x The exception. maybe we should get some information from that....
     */
    protected void defaultLogError(Issue.Category category, NetworkObject node) {
        issueQueue.add( new Issue( category, node ) );
    }

    private class CustomUncaughtExceptionHandler implements Thread.UncaughtExceptionHandler {

        @Override
        public void uncaughtException(Thread t, Throwable e) {
            signal.add( NO_RESULT );
            logger.info( e.getLocalizedMessage() );
        }
    }

}
