# https://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-macos

FROM openjdk:18
ADD target/ParentPOMProj.jar /usr/local/lib/warehouse.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","/usr/local/lib/warehouse.jar","--add-modules","jdk.incubator.foreign","--add-exports","java.base/jdk.internal.misc=ALL-UNNAMED","--add-opens","java.base/jdk.internal.util=ALL-UNNAMED"]