# https://stackoverflow.com/questions/21964709/how-to-set-or-change-the-default-java-jdk-version-on-macos

FROM openjdk:18-jre-slim
ADD /target/warehouse-1.0-SNAPSHOT.jar /usr/local/lib/warehouse.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar","/usr/local/lib/warehouse.jar"]