package dk.ku.di.dms.vms.modb.query.planner.operator.insert;

/**
 * For each stream consumed, a result must be generated by this operator
 */
public interface OneToOneProducer<T> extends ContinuousStreamOperator {

    T getNext();

}
