package dk.ku.di.dms.vms.modb.manipulation.insert;

/**
 * For each stream consumed, a result must be generated by this operator
 */
public interface OneToOneProducer<T> extends ContinuousInputStreamOperator {

    T getNext();

}
